### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Pixelbot2** [PixelExtended/official_devices#10]
## Device you want to apply for
```
Poco M2 and Redmi 9 (Lava)
```

## Device tree sources

```
https://github.com/Pixelbot2/Lava_Device_trees
https://github.com/Redmi-MT6768/android_kernel_xiaomi_mt6768
https://github.com/Pixelbot2/MT6768_android_vendor_ims
```

## Number of ROM's you maintain officially
```
only arrow os
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
i build locally
```
## Free trial user or paid user?
```
free
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
https://t.me/Pixelbot123
```

### GitHub username
```
https://github.com/Pixelbot2
```

**Comment by ralf979** [comment]
I don't think in Arrow they make you officially release with this dt
And I advise you to make it private or delete it
However it is not possible

**Comment by Pixelbot2** [comment]
Sould I use arrow os trees
