### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by agathasenpai** [PixelExtended/official_devices#12]
## Device you want to apply for
```
Redmi Note 11 / 11 NFC (spes/spesn)
```

## Device tree sources

```
https://github.com/agathasenpai/device_xiaomi_spes/tree/13-pex
https://github.com/agathasenpai/kernel_xiaomi_spes
https://github.com/agathasenpai/vendor_xiaomi_spes
```

## Number of ROM's you maintain officially
```
2
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Server
```
## Free trial user or paid user?
```
Paid user
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
@agathasenpai7
```

### GitHub username
```
agathasenpai
```

**Comment by iamimmanuelraj** [comment]
LGTM
CR  +1

@heisinbug @ralf979

**Comment by heisinbug** [comment]
+1

**Comment by iamimmanuelraj** [comment]
Trees doesnt exist (ATM). Revisited to accepet and do a final check but nothing exists. REJECTED
