### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by JayanthKandula** [PixelExtended/official_devices#13]
## Device you want to apply for
```
Poco F4/Redmi k40S
```

## Device tree sources

```
https://github.com/JayanthKandula/device_xiaomi_munch/tree/trece
https://github.com/JayanthKandula/device_xiaomi_sm8250-common/tree/trece
https://github.com/JayanthKandula/kernel_xiaomi_sm8250
https://gitlab.com/jayanth-coder/vendor-xiaomi-munch/-/tree/thirteen
https://gitlab.com/jayanth-coder/vendor-xiaomi-sm-8250-common/-/tree/thirteen
```

## Number of ROM's you maintain officially
```
0
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
I build locally 
```
## Free trial user or paid user?
```
N/A
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
https://t.me/Jayanthk
```

### GitHub username
```
https://github.com/JayanthKandula
```

**Comment by iamimmanuelraj** [comment]
Kerneltoast did [THIS[(https://github.com/JayanthKandula/kernel_xiaomi_sm8250/commit/4bb3932a966955740cde82917801cabe974526f7) for his pixels. Its not for all devices. it needs to be adapted to work with custom gcams. Its not even needed. i wonder why u picked it without modifying.

We dont even use that branches https://github.com/JayanthKandula/device_xiaomi_sm8250-common/commit/927aa1b38dc366af69dc45baea0b2b6e45782b44

Its not built in hal iirc https://github.com/JayanthKandula/device_xiaomi_sm8250-common/commit/0ae80e26f53bfd7aeefa86f3c30e37d194e4f890

I can very well see you are blink picking and have no idea what it does.

CR -1.
