### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by the-deepongi** [PixelExtended/official_devices#16]
---
name: Device maintainer form
about: Apply to be a maintainer at PEX here
title: New maintainer
assignees: [heisinbug, ralf979, iamimmanuelraj]
---

## Device you want to apply for
```
instantnoodle
```

## Device tree sources

```
git@github.com/the-deepongi/android_device_oneplus_instantnoodle-pex
git@github.com/the-deepongi/android_kernel_oneplus_sm8250-pex
git@github.com/the-deepongi/android_device_oneplus_sm8250-common-pex
git@github.com/the-deepongi/android_hardware_oneplus
git@github.com/the-deepongi/proprietary_vendor_oneplus_sm8250-common
git@github.com/the-deepongi/proprietary_vendor_oneplus_instantnoodle
git@github.com/the-deepongi/hardware_oplus
```

## Number of ROM's you maintain officially
```
None.
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Locally.
```
## Free trial user or paid user?
```
Free trial user.
```

## Any Exceptions/special concern?
```
No.
```

### Telegram username
```
@deepongi
```

### GitHub username
```
deepongi-labs
```

**Comment by iamimmanuelraj** [comment]
CR : -2
