### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by the-deepongi** [PixelExtended/official_devices#17]
---
name: Device maintainer form
about: Apply to be a maintainer at PEX here
title: New maintainer
assignees: [heisinbug, ralf979, iamimmanuelraj]
---

## Device you want to apply for
```
veux
```

## Device tree sources

```
https://github.com/deepongi-labs/android_device_xiaomi_veux-kernel-pex
https://github.com/deepongi-labs/android_kernel_xiaomi_sm6375-pex
https://github.com/deepongi-labs/android_device_xiaomi_veux-pex
https://github.com/deepongi-labs/android_vendor_xiaomi_veux-pex
```

## Number of ROM's you maintain officially
```
None
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Locally
```
## Free trial user or paid user?
```
Free trial user
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
@deepongi
```

### GitHub username
```
deepongi-labs
```

**Comment by iamimmanuelraj** [comment]
CR : -2
