### ISSUE TITLE
ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by Mikdadali** [PixelExtended/official_devices#18]
## Device you want to apply for
Mi 11 Lite NE 5g

Your device name
lisa

## Device tree sources

https://github.com/Mikdadali/device_xiaomi_lisa
https://github.com/Mikdadali/vendor_lisa
https://github.com/Mikdadali/android_kernel_xiaomi_lisa

## Number of ROM's you maintain officially
1

Insert here
https://github.com/SuperiorOS

## Do you build locally or rely on server if server what cloud service provider do you use ?
I am using NewEraServer
https://web.telegram.org/z/#-1764323428

## Free trial user or paid user?
Paid

## Any Exceptions/special concern?
No

### Telegram username
```
Your Telegram username
@ali_171821

### GitHub username
```
Your GitHub username
Mikdadali

**Comment by iamimmanuelraj** [comment]
The tree has no relevence with PixelExtended

**Comment by heisinbug** [comment]
Adapt the trees for pex , if you have already built and published publicly then we can move ahead if not request you to do the same and then apply . Thank you .

**Comment by Mikdadali** [comment]
Yes i have already built 5.3, 5.4, 5.5

**Comment by iamimmanuelraj** [comment]
Show the builds that you have published (Like XDA)
You built we agree, but its not made specifically for PEX. 
Its not adapted to match official requirements also (Like defining dependencies etc
)

**Comment by heisinbug** [comment]
We will be closing this issue by this weekend if no response received 😶
