### ISSUE TITLE
New maintainer For Poco X3 (Surya)

### ISSUE THREAD

**Issue by KUIpru** [PixelExtended/official_devices#19]
## Device you want to apply for
Poco x3/nfc (surya/karna)

Your device name
Karna(surya)

## Device tree sources
https://github.com/KUIpru/device_xiaomi_surya
https://github.com/KUIpru/vendor_xiaomi_surya
https://github.com/KUIpru/android_kernel_xiaomi_surya-1

```

## Number of ROM's you maintain officially
1

Insert here
Cherish OS
https://cherishos.com/


## Do you build locally or rely on server if server what cloud service provider do you use ?
I am using NewEraServer
https://web.telegram.org/z/#-1764323428

## Free trial user or paid user?
Paid user
Insert here
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
Your Telegram username
https://t.me/kuimunch

### GitHub username
```
Your GitHub username
https://github.com/KUIpru

**Comment by KUIpru** [comment]
sorry but i mistakenly gave wrong branch 
correct branch is pex 
https://github.com/KUIpru/device_xiaomi_surya/tree/pex

**Comment by iamimmanuelraj** [comment]
You just said u gave wrong branch by mistake but the commit says as yesterday. Lies ?
cr -1

**Comment by KUIpru** [comment]
tree was renamed sir .

**Comment by ralf979** [comment]
I have been following the discussion from the beginning
You had the branch pex without having done the bringup... You did this two days after making the request. So either you've never built pex, or these aren't the trees you use to build.

**Comment by KUIpru** [comment]
Sir actually I applied when my branch dt didn't had bringup . After applying i did bringup and tried to make build . Build was preety successful . And u can see it on Surya device channel and group and i used same trees that i shared u .
So in a nutshell I applied before proper bringup(in excitement ) , but i did bringup after applying and made rom successfully . I m using same dt , kernel , vendor etc . That are in my GitHub and already I have provided u link here .

**Comment by ralf979** [comment]
for excitement you can destroy a device.
we don't need speed and superficiality, but stability.

for me the discussion is closed.
thanks for trying

**Comment by iamimmanuelraj** [comment]
CR -2
