### ISSUE TITLE
New maintainer for Poco F4 / Redmi k40s (munch)

### ISSUE THREAD

**Issue by ad1tyx666** [PixelExtended/official_devices#20]
## Device you want to apply for
```
munch
```

## Device tree sources

```
https://github.com/Vincent4440/device_xiaomi_munch
https://github.com/Vincent4440/munch_device_xiaomi_sm8250-common
https://github.com/Vincent4440/kernel_xiaomi_munch
https://gitlab.com/Vincent4440/vendor_xiaomi_munch.git
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_sm8250-common
```

## Number of ROM's you maintain officially
```
none
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
locally
```
## Free trial user or paid user?
```
Free trial 
```

## [MUST] Paste your build post link?
```
https://t.me/PocoF4updates/564 & https://t.me/PocoF4IDUpdate/753
```

### Telegram username
```
https://t.me/vinc3nt_exe
```

### GitHub username
```
https://github.com/Vincent4440
```

**Comment by heisinbug** [comment]
+1

**Comment by iamimmanuelraj** [comment]
+1

**Comment by iamimmanuelraj** [comment]
Why is there no XDA?

**Comment by ad1tyx666** [comment]
Ohh actually I thought we had to post the rom on xda after it gets official, sorry for the inconvenience

**Comment by heisinbug** [comment]
Accepted

**Comment by ad1tyx666** [comment]
Thanks you guys for taking me in
