### ISSUE TITLE
New maintainer For POCO X3

### ISSUE THREAD

**Issue by KUIxd** [PixelExtended/official_devices#21]
## Device you want to apply for
```
Your device name
Poco x3 (surya) 

## Device tree sources
https://github.com/KUIpru/device_xiaomi_surya
https://github.com/KUIpru/android_kernel_xiaomi_surya
https://github.com/KUIpru/android_vendor_xiaomi_surya
```

## Number of ROM's you maintain officially
1
Insert here
https://cherishos.com/

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Local
```
## Free trial user or paid user?
Free
```

## [MUST] Paste your build post link?
```
https://t.me/kui_builds/5616

### Telegram username
```
https://t.me/unbanmeShroud

### GitHub username
```
https://github.com
```

**Comment by heisinbug** [comment]
-1

**Comment by heisinbug** [comment]
Blinding cherry-picking and commiting over a pre-built trees without knowing the application behind it . we don't want to break devices here but wish you re-apply with a better version of yours 😊

**Comment by KUIxd** [comment]
everything i implemented is not blindly picked , those are properly tested 
and u selected a guy who literally did 2 commits himself . 
i will not re-apply until i will see a better version of yours 😊

**Comment by iamimmanuelraj** [comment]
@KUIpru 

Doing 2 commits and know what he does and doing it properly > Doing many unknown thngs

1. U dont have dependencies
2. U made this commit https://github.com/KUIpru/device_xiaomi_surya/commit/cbc8126121c0f3a64afa504055cc6db6943b767b

No idea where the package is from...no source is there for it. Nothing. No idea. 

Do you still say u dont blindly pick and tested all stuff?
I dont want to argue but i want to make you understand that there is always space for improvement and be better
We would love to see you apply back with proper things in tree .

PS: We stoped you cause we dont want to have bad name on our maintainers and also our OS and not to blame you. Hope you understand :smile: 

Edit : Tagged KuiPru

**Comment by KUIpru** [comment]
@iamimmanuelraj https://github.com/KUIpru/device_xiaomi_surya/commit/cbc8126121c0f3a64afa504055cc6db6943b767b 
that commit is for miui cam and the source is in my gitlab , that project is forced private , i could give u it's access but u didn't told me about that before closing the issue .

**Comment by KUIxd** [comment]
@iamimmanuelraj lmao ded
this commit https://github.com/KUIpru/device_xiaomi_surya/commit/cbc8126121c0f3a64afa504055cc6db6943b767b 
source is in my gitlab but sadly that was forced private , if u asked me about this before closing the issue , then i could give u it's access .
btw thanks for your assistance and guidance 
ig i learnt a new lesson today 
anyways let's move ahead , world is vast 😁

**Comment by heisinbug** [comment]
> everything i implemented is not blindly picked , those are properly tested 
> and u selected a guy who literally did 2 commits himself . 
> i will not re-apply until i will see a better version of yours 😊

We don't recruit based on how much commits you have but how clean and maintained your trees are that may produce a stable build .It's okay to have zero commits over a good tree and still recruit rather than having tons of Placebo. 

Anyways if I would have to reject you with another reason it would be your wrong attitude trying to be savage . 

I am just loving the fact how negatively you took your rejection and turned this issue into an "ISSUE" .

**Comment by iamimmanuelraj** [comment]
> @iamimmanuelraj lmao ded
> this commit https://github.com/KUIpru/device_xiaomi_surya/commit/cbc8126121c0f3a64afa504055cc6db6943b767b 
> source is in my gitlab but sadly that was forced private , if u asked me about this before closing the issue , then i could give u it's access .
> btw thanks for your assistance and guidance 
> ig i learnt a new lesson today 
> anyways let's move ahead , world is vast 😁

Well, there is nothing to laugh your ass off. I dont see any good in having closed source stuff in open source project and applying for official. And I wanted to say what aryan said.
