### ISSUE TITLE
New maintainer for Redmi 10/10 Prime/10 2022 (Selene)

### ISSUE THREAD

**Issue by atharvnegi** [PixelExtended/official_devices#22]
## Device you want to apply for
```
Your device name
```

## Device tree sources

```
https://github.com/selene-devs/android_device_xiaomi_selene
https://github.com/selene-devs/android_kernel_xiaomi_selene
https://github.com/selene-devs/android_vendor_xiaomi_selene
```

## Number of ROM's you maintain officially
```
Crystal os
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Shared server
```
## Free trial user or paid user?
```
Free
```

## [MUST] Paste your build post link?
```
https://t.me/atharv2951_builds
```

### Telegram username
```
@atharv2951
```

### GitHub username
```
github.com/atharvnegi
```

**Comment by heisinbug** [comment]
https://github.com/selene-devs/android_device_xiaomi_selene/blob/lineage-20/lineage_selene.mk 

help me clear my confusion here are you applying for pex or los ?

**Comment by heisinbug** [comment]
oh wait you pasted a org tree here suddenly gives me amateur impression , re-apply if you understand how it works 😊
