### ISSUE TITLE
New maintainer for Redmi Note 8/8t (Ginkgo/Willow)

### ISSUE THREAD

**Issue by GioKas93** [PixelExtended/official_devices#24]
## Device you want to apply for
```
Redmi Note 8/8t (Ginkgo/Willow)
```

## Device tree sources

```
https://github.com/GioKas93/device_xiaomi_ginkgo
https://github.com/GioKas93/vendor_xiaomi_ginkgo
https://github.com/GioKas93/kernel_xiaomi_ginkgo_Lightning-Kernel (changed kernel since unofficial release)
```

## Number of ROM's you maintain officially
```
None
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Dedicated server on Hetzner
```
## Free trial user or paid user?
```
Paid
```

## [MUST] Paste your build post link?
```
https://t.me/rn8updates/6942
```

### Telegram username
```
https://t.me/GioKas93
```

### GitHub username
```
https://github.com/GioKas93
```

**Comment by ralf979** [comment]
Lol accepted
