### ISSUE TITLE
New maintainer for Mi11x,PocoF3,RedmiK40(Alioth)

### ISSUE THREAD

**Issue by Chaitanyakm** [PixelExtended/official_devices#26]
## Device you want to apply for
```
Mi11x,PocoF3,RedmiK40(Alioth)
```

## Device tree sources

```
https://github.com/Chaitanyakm/device_xiaomi_alioth
https://github.com/Chaitanyakm/vendor_xiaomi_alioth
https://github.com/EmanuelCN/kernel_xiaomi_sm8250
https://github.com/Chaitanyakm/device_xiaomi_sm8250-common
https://github.com/Chaitanyakm/vendor_xiaomi_sm8250-common
```

## Number of ROM's you maintain officially
```
2
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
I Do builds on both local machine and Google cloud platform servers
```
## Free trial user or paid user?
```
Free Trial User
```

## [MUST] Paste your build post link?
```
https://t.me/pocoF3GlobalUpdates/1779
```

### Telegram username
```
@chaitanyakm
```

### GitHub username
```
Chaitanyakm
```

**Comment by heisinbug** [comment]
Which two ROMs are you maintaining rn ?

**Comment by Chaitanyakm** [comment]
> Which two ROMs are you maintaining rn ?

Ancient for mido and realme X2
And droidxui for alioth

**Comment by iamimmanuelraj** [comment]
Dont you think taking this up will make you super busy? Will you be able to sustainably give updates?

**Comment by Chaitanyakm** [comment]
> Dont you think taking this up will make you super busy? Will you be able to sustainably give updates?

Yes I can give updates consistently previous year I was maintaining 4 roms but I need to leave development for some personal reasons at that time

**Comment by iamimmanuelraj** [comment]
Multiple ROM for one device

And

Multiple devices for one ROM

The above two combo only seems to work best as far as i know (Exception exist). I fear if you will be able to manage multiple device and multiple roms

CR -1

**Comment by heisinbug** [comment]
> Dont you think taking this up will make you super busy? Will you be able to sustainably give updates?

Agree with what Immanuel said here , tbh we don't want to steal your precious little "personal time" from you that you get after maintaining numerous ROMs and contributing towards community , that's an little too much responsibility for you .

**Comment by ralf979** [comment]
I think we can close here :)

**Comment by Chaitanyakm** [comment]
Ok so I'm gonna keep maintaining unofficial until someone else takes official

**Comment by heisinbug** [comment]
> Ok so I'm gonna keep maintaining unofficial until someone else takes official

:)
