### ISSUE TITLE
New maintainer for Mi11x,PocoF3,RedmiK40(Alioth)

### ISSUE THREAD

**Issue by Chaitanyakm** [PixelExtended/official_devices#28]
## Device you want to apply for
```
Mi11x,PocoF3,RedmiK40(Alioth)
```

## Device tree sources

```
https://github.com/Chaitanyakm/device_xiaomi_alioth
https://github.com/Chaitanyakm/vendor_xiaomi_alioth
https://github.com/EmanuelCN/kernel_xiaomi_sm8250
https://github.com/Chaitanyakm/device_xiaomi_sm8250-common
https://github.com/Chaitanyakm/vendor_xiaomi_sm8250-common
```

## Number of ROM's you maintain officially
```
1
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
i build on both gcp and local machine
```
## Free trial user or paid user?
```
Free User
```

## [MUST] Paste your build post link?
```
https://t.me/PocoF3GlobalOfficial/1239116
```

### Telegram username
```
@chaitanyakm
```

### GitHub username
```
chaitanyakm
```

**Comment by ralf979** [comment]
Hello 
I only see one released build. Can you also show me the other two please (if you read the note it takes 3 builds of 3 security patches) 
Thanks

**Comment by Chaitanyakm** [comment]
> Hello I only see one released build. Can you also show me the other two please (if you read the note it takes 3 builds of 3 security patches) Thanks

here are all 3 builds
https://t.me/PocoF3GlobalOfficial/1239116
https://t.me/pocoF3GlobalUpdates/1779
https://t.me/pocoF3GlobalUpdates/1799

**Comment by ralf979** [comment]
Ok thanks, we also wait for the response of the other guys :)

**Comment by Chaitanyakm** [comment]
> Ok thanks, we also wait for the response of the other guys :)

Ok 👍

**Comment by heisinbug** [comment]
> Ok thanks, we also wait for the response of the other guys :)

+1
