### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by jaymistry258** [PixelExtended/official_devices#29]
## Device you want to apply for
```
Xiaomi Poco X2 (Phoenix)
```

## Device tree sources

```
https://github.com/jaymistry258/android_device_xiaomi_phoenix.git
https://github.com/jaymistry258/android_kernel_xiaomi_phoenix.git
https://github.com/jaymistry258/android_vendor_xiaomi_phoenix.git
```

## Number of ROM's you maintain officially
```
Zero
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
I build locally using my own system. 
```
## Free trial user or paid user?
```
Everything is free from me I don't ask for any kind of payment to anyone for my builds.
```

## [MUST] Paste your build post link?
```
https://t.me/Poco_X2_Builds/4761
```

### Telegram username
```
jaymistry258
```

### GitHub username
```
jaymistry258
```

**Comment by iamimmanuelraj** [comment]
cr -1

**Comment by jaymistry258** [comment]
Sorry i don't understand what is cr -1 ?

**Comment by iamimmanuelraj** [comment]
It's for team members internally. The rest of the panel will let you know the result

**Comment by ralf979** [comment]
Thanks, but no.
