### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by olhotorto** [PixelExtended/official_devices#3]
## Device you want to apply for
```
Xiaomi Redmi Note 10 Pro/Max (sweet/sweetin)
```

## Device tree sources
```
https://github.com/olhotorto/device_xiaomi_sweet
https://github.com/olhotorto/kernel_xiaomi_sweet
https://gitlab.com/PixelOS-Devices/playgroundtc
https://github.com/olhotorto/vendor_xiaomi_sweet
```

## Number of ROM's you maintain officially
```
ROMs builded for personal use(sweet/sweetin)

PixelExperience (A12L)
Evolution X (A12L)

ROMs (unofficial) that I released on my old device(platina):

dotOS (A11)
Project Sakura (A11)
Spark OS (A12L)
Superior OS (A12L)
Evolution X (A12L)
```

## Any Exceptions/special concern?
```
1:

This "olhotorto" account was created recently (I deleted my main account for personal reasons). But I am familiar with git for a long time, I am fully capable of handling any challenge at my level.

2:

I am fully focused on my own stuff, most likely I will always be updating the ROM if I get accepted. 

3:

I'm still learning English. (But for now, I have no difficulty from my point of view)
```

### Telegram username
```
olhotorto
```

### GitHub username
```
olhotorto
```

**Comment by heisinbug** [comment]
do you build locally or rely on server if so what cloud provider do you use ?

**Comment by olhotorto** [comment]
> do you build locally or rely on server if so what cloud provider do you use ?

VM.(Microsoft Azure)

**Comment by heisinbug** [comment]
> > do you build locally or rely on server if so what cloud provider do you use ?
> 
> Server(Microsoft Azure)

how long you will have this server ?

**Comment by olhotorto** [comment]
> > > do you build locally or rely on server if so what cloud provider do you use ?
> > 
> > 
> > Server(Microsoft Azure)
> 
> how long you will have this server ?

Until I can't pay

**Comment by heisinbug** [comment]
This application is for A13 , are you aware of this ?

**Comment by olhotorto** [comment]
> This application is for A13 , are you aware of this ?

Yup

**Comment by heisinbug** [comment]
have you booted , where is tree link ?

**Comment by olhotorto** [comment]
> have you booted , where is tree link ? i see only snow branch there .

It's all up there. But no, I haven't tried booting with PEX 13, just spark a13 and everything was working fine

**Comment by iamimmanuelraj** [comment]
Show some of your XDA works of the roms you mentioned in the list above

**Comment by heisinbug** [comment]
> > have you booted , where is tree link ? i see only snow branch there .
> 
> It's all up there. But no, I haven't tried booting with PEX 13, just spark a13 and everything was working fine

boot pex a13 update tree branch and we're good to go .

**Comment by olhotorto** [comment]
> Show some of your XDA works of the roms you mentioned in the list above

I don't have XDA. Posted in telegram

Links:

https://t.me/mi8liteupdate/1280
https://t.me/mi8liteupdate/1223
https://t.me/mi8liteupdate/1225
https://t.me/mi8liteupdate/1239
https://t.me/mi8liteupdate/1241

Some have some bugs because I was still learning. But evox is totally stable

**Comment by olhotorto** [comment]
> > > have you booted , where is tree link ? i see only snow branch there .
> > 
> > 
> > It's all up there. But no, I haven't tried booting with PEX 13, just spark a13 and everything was working fine
> 
> boot pex a13 update tree branch and we're good to go .

PeX 13 source can it already be build?? I will rebase my tree and make it

**Comment by heisinbug** [comment]
> > > > have you booted , where is tree link ? i see only snow branch there .
> > > 
> > > 
> > > It's all up there. But no, I haven't tried booting with PEX 13, just spark a13 and everything was working fine
> > 
> > 
> > boot pex a13 update tree branch and we're good to go .
> 
> PeX 13 source can it already be build?? I will rebase my tree and make it

yes it's buildable also XDA is MUST to release your builds .

**Comment by olhotorto** [comment]
> 

I will create an account on XDA soon

**Comment by olhotorto** [comment]
> > > > > have you booted , where is tree link ? i see only snow branch there .
> > > > 
> > > > 
> > > > It's all up there. But no, I haven't tried booting with PEX 13, just spark a13 and everything was working fine
> > > 
> > > 
> > > boot pex a13 update tree branch and we're good to go .
> > 
> > 
> > PeX 13 source can it already be build?? I will rebase my tree and make it
> 
> yes it's buildable also XDA is MUST to release your builds .

Ok, I will create an account on XDA soon

**Comment by heisinbug** [comment]
> > > > > > have you booted , where is tree link ? i see only snow branch there .
> > > > > 
> > > > > 
> > > > > It's all up there. But no, I haven't tried booting with PEX 13, just spark a13 and everything was working fine
> > > > 
> > > > 
> > > > boot pex a13 update tree branch and we're good to go .
> > > 
> > > 
> > > PeX 13 source can it already be build?? I will rebase my tree and make it
> > 
> > 
> > yes it's buildable also XDA is MUST to release your builds .
> 
> What is the status of this application? under review¿ Waiting¿

Waiting for your update to boot pex 5.0 (13) and update trees with "trece" branch name

**Comment by olhotorto** [comment]
> > > > > > > have you booted , where is tree link ? i see only snow branch there .
> > > > > > 
> > > > > > 
> > > > > > It's all up there. But no, I haven't tried booting with PEX 13, just spark a13 and everything was working fine
> > > > > 
> > > > > 
> > > > > boot pex a13 update tree branch and we're good to go .
> > > > 
> > > > 
> > > > PeX 13 source can it already be build?? I will rebase my tree and make it
> > > 
> > > 
> > > yes it's buildable also XDA is MUST to release your builds .
> > 
> > 
> > What is the status of this application? under review¿ Waiting¿
> 
> Waiting for your update to boot pex 5.0 (13) and update trees with "trece" branch name , all the best 👍

Ok, I'll rebase and clone the sources. And try to boot

**Comment by olhotorto** [comment]
> have you booted , where is tree link ? i see only snow branch there .

I have already rebased the trees. Now I'll just wait to clone the source so I can start build

**Comment by olhotorto** [comment]
> > > > > > > have you booted , where is tree link ? i see only snow branch there .
> > > > > > 
> > > > > > 
> > > > > > It's all up there. But no, I haven't tried booting with PEX 13, just spark a13 and everything was working fine
> > > > > 
> > > > > 
> > > > > boot pex a13 update tree branch and we're good to go .
> > > > 
> > > > 
> > > > PeX 13 source can it already be build?? I will rebase my tree and make it
> > > 
> > > 
> > > yes it's buildable also XDA is MUST to release your builds .
> > 
> > 
> > What is the status of this application? under review¿ Waiting¿
> 
> Waiting for your update to boot pex 5.0 (13) and update trees with "trece" branch name , all the best 👍

![Screenshot_20220925-211051](https://user-images.githubusercontent.com/114243782/192172091-1d62ed6c-5881-49f9-9857-2a009fcf9edf.png)

Done. Check my trees...

Offtopic:

Pick commit:-> https://github.com/PixelExtended/manifest/commit/20a254366c6e210acc754e34ef282aa5c724d61d <-:to default branch (trece)

If not:-> https://pastebin.com/wrmr2Wtv

**Comment by olhotorto** [comment]
> > > > > > > > have you booted , where is tree link ? i see only snow branch there .
> > > > > > > 
> > > > > > > 
> > > > > > > It's all up there. But no, I haven't tried booting with PEX 13, just spark a13 and everything was working fine
> > > > > > 
> > > > > > 
> > > > > > boot pex a13 update tree branch and we're good to go .
> > > > > 
> > > > > 
> > > > > PeX 13 source can it already be build?? I will rebase my tree and make it
> > > > 
> > > > 
> > > > yes it's buildable also XDA is MUST to release your builds .
> > > 
> > > 
> > > What is the status of this application? under review¿ Waiting¿
> > 
> > 
> > Waiting for your update to boot pex 5.0 (13) and update trees with "trece" branch name , all the best 👍
> 
> ![Screenshot_20220925-211051](https://user-images.githubusercontent.com/114243782/192172091-1d62ed6c-5881-49f9-9857-2a009fcf9edf.png)
> 
> Done. Check my trees...
> 
> Offtopic:
> 
> Pick commit:-> [PixelExtended/manifest@20a2543](https://github.com/PixelExtended/manifest/commit/20a254366c6e210acc754e34ef282aa5c724d61d) <-:to default branch (trece)
> 
> If not:-> https://pastebin.com/wrmr2Wtv

@iamimmanuelraj @heisinbug

**Comment by olhotorto** [comment]
> > > > > > > > > have you booted , where is tree link ? i see only snow branch there .
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It's all up there. But no, I haven't tried booting with PEX 13, just spark a13 and everything was working fine
> > > > > > > 
> > > > > > > 
> > > > > > > boot pex a13 update tree branch and we're good to go .
> > > > > > 
> > > > > > 
> > > > > > PeX 13 source can it already be build?? I will rebase my tree and make it
> > > > > 
> > > > > 
> > > > > yes it's buildable also XDA is MUST to release your builds .
> > > > 
> > > > 
> > > > What is the status of this application? under review¿ Waiting¿
> > > 
> > > 
> > > Waiting for your update to boot pex 5.0 (13) and update trees with "trece" branch name , all the best 👍
> > 
> > 
> > ![Screenshot_20220925-211051](https://user-images.githubusercontent.com/114243782/192172091-1d62ed6c-5881-49f9-9857-2a009fcf9edf.png)
> > Done. Check my trees...
> > SELinux Enforcing.
> 
> @iamimmanuelraj @heisinbug

I've also created the XDA account -> https://forum.xda-developers.com/m/olhotorto.12303655/ <- I'm totally ready to post my works there

**Comment by olhotorto** [comment]
![Uploading Screenshot_20221003-213553.png…]()

**Comment by olhotorto** [comment]
![Screenshot_20221003-213553](https://user-images.githubusercontent.com/114243782/193709955-1842cc6d-cde4-4693-b0fe-4838e7878efa.png)

**Comment by heisinbug** [comment]
Accepted
