### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by chriscfilho** [PixelExtended/official_devices#30]
## Device you want to apply for
```
Samsung Galaxy M52 5G (m52xq)
```

## Device tree sources

```
https://github.com/eugostodetortas/android_device_samsung_m52xq
https://github.com/eugostodetortas/android_device_samsung_sm7325-common
https://github.com/Simon1511/android_vendor_samsung_sm7325-common
https://github.com/Simon1511/android_vendor_samsung_m52xq
https://github.com/Simon1511/android_kernel_samsung_sm7325
```

## Number of ROM's you maintain officially
```
0
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Server
```
## Free trial user or paid user?
```
Free trial
```

## [MUST] Paste your build post link?
```
https://t.me/M52REPO/118
```

### Telegram username
```
@eugostodetortas
```

### GitHub username
```
eugostodetortas
```

**Comment by iamimmanuelraj** [comment]
CR -1 from my side

cc @heisinbug @heisinbug
