### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Notganesh** [PixelExtended/official_devices#31]
## Device you want to apply for
```
Your device name
Redmi 9T / Poco M3

## Device tree sources
-->
``
https://gitlab.com/Juiceoss/android_device_xiaomi_chime.git
https://gitlab.com/Juiceoss/android_vendor_xiaomi_chime.git
https://gitlab.com/Juiceoss/kernel-xiaomi-chime.git
```

## Number of ROM's you maintain officially
```
Not Yet 
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Server
```
## Free trial user or paid user?
```
Free trial 
```

## [MUST] Paste your build post link?
```
https://t.me/dumps_chime
```

### Telegram username
@Notganesh
Your Telegram username
@Notganesh

### GitHub username
```
Your GitHub username
@Notaganesh

**Comment by ralf979** [comment]
-1 for me

**Comment by iamimmanuelraj** [comment]
Hi,

Thank you for your interest in becoming a maintainer of our open source project. We appreciate your enthusiasm and dedication to the project.

After careful consideration, we have decided not to move forward with your application at this time. We received many applications from highly qualified candidates and unfortunately, we cannot accept everyone.

We encourage you to continue contributing to the project and participating in our community. We value your contributions and hope that you will continue to be involved.

Thank you again for your interest in our project.

Best regards,
Immanuel Raj
