### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ramshell68** [PixelExtended/official_devices#32]
## Device you want to apply for
```
POCO M3 Pro / Redmi Note 10T / 10 5G / 11 SE
```

## Device tree sources
-->
```
https://github.com/ramshell688/android_device_xiaomi_camellia
https://github.com/ramshell688/android_device_xiaomi_camellia-kernel
https://github.com/ramshell688/android_vendor_xiaomi_camellia
```

## Number of ROM's you maintain officially
```
1
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
DO Server
```
## Free trial user or paid user?
```
Free trial user
```

## [MUST] Paste your build post link?
```
https://t.me/ramsprojects
```

### Telegram username
```
@ramshell688
```

### GitHub username
```
ramshell688
```

**Comment by iamimmanuelraj** [comment]
LGTM 👍 

Please remove those custom mods. Do not modify anything in the source.

CC @heisinbug @ralf979

**Comment by ramshell68** [comment]
Done sir
