### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by JYRRC** [PixelExtended/official_devices#35]
## Device you want to apply for
```
Pocophone F5 / Redmi note 12 turbo (Marble)
```

## Device tree sources

```
https://github.com/JYRRC/android_device_xiaomi_marble
https://github.com/JYRRC/android_kernel_xiaomi_marble
https://gitlab.com/JYRRC/vendor_xiaomi_marble
```

## Number of ROM's you maintain officially
```
One
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Locally Linux Ubuntu
```
## Free trial user or paid user?
```
Free User
```

## [MUST] Paste your build post link?
```
https://t.me/Crdroid_Marble/2238
```

### Telegram username
```
@JYR_RC
```

### GitHub username
```
https://github.com/JYRRC

**Comment by ralf979** [comment]
Have you read what it takes to request maintenance? especially the mandatory one?
where are the 3 builds of 3 versions ? I only see one.

make the request when you have made 3 unofficial releases
Thank you

**Comment by JYRRC** [comment]
Okay, I'll do it, please keep me in mind, I'll continue until I meet the requirements, thank you.

**Comment by ralf979** [comment]
Sure !!

**Comment by iamimmanuelraj** [comment]
CR: -1
