### ISSUE TITLE
 Applying for maintaining official Pixel Extended build for Xiaomi 11 Lite NE 5G (lisa)

### ISSUE THREAD

**Issue by Amit152505** [PixelExtended/official_devices#37]
## Device you want to apply for
```
Xiaomi 11 Lite NE 5G (lisa)
```

## Device tree sources

```
https://github.com/Amit152505/device_xiaomi_lisa
https://github.com/Amit152505/kernal_xiaomi_lisa
https://github.com/Amit152505/vendor_xiaomi_lisa
```

## Number of ROM's you maintain officially
```
Official:- None
Unofficial:- 1 [DerpFest]
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Ubuntu cloud server by Azure
```
## Free trial user or paid user?
```
Paid user
```

## [MUST] Paste your build post link?
```
https://t.me/Xiaomi11LiteNE/413302
or
https://t.me/derpfest_lisa_unofficial/2918
```

### Telegram username
```
nicolas1525
```

### GitHub username
```
Amit152505
```

**Comment by ralf979** [comment]
What should we do with the derpfest build? Where are the 3 unofficial builds of pex? 
You have read the requirements to request mainteinership?

**Comment by Amit152505** [comment]
So I need three different build for three different security patch?

**Comment by ralf979** [comment]
Yes

**Comment by Amit152505** [comment]
I'm really sorry for applying without reading the guidelines. I'll apply after 3 months.

**Comment by HarishShende** [comment]
i have one issue i want to know is pixel extended rom work on realme 7 device?
