### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by HarishShende** [PixelExtended/official_devices#38]
## Device you want to apply for
```to know working or not
Your device name
```Realme 7

## Device tree sources
<!--
* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship should be proper
* Add common trees if applicable
-->
```
https://github.com/user/device_brand_codename
https://github.com/user/kernel_brand_codename
https://github.com/user/vendor_brand_codename
```

## Number of ROM's you maintain officially
```
Insert here
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Insert here
```
## Free trial user or paid user?
```
Insert here
```

## [MUST] Paste your build post link?
```
Insert here
```

## Contact

### Telegram username
```
Your Telegram username
```

### GitHub username
```
Your GitHub username
```

**Comment by ralf979** [comment]
Why didn't you complete the format?

**Comment by HarishShende** [comment]
Sorry i am new on GitHub and i don't know how to use but please can you
tell me is pixel extended is compatible for realme 7

**Comment by ralf979** [comment]
it is not the place to ask and not open more issues
thanks
