### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by AhmedKazim-Dev** [PixelExtended/official_devices#5]
## Device you want to apply for
```
Miatoll
```

## Device tree sources

```
https://github.com/AhmedKazim-Dev/device_xiaomi_miatoll
https://github.com/AhmedKazim-Dev/device_xiaomi_sm6250-common
https://github.com/ProjectVelvet/android_kernel_sm6250
https://github.com/AhmedKazim-Dev/vendor_xiaomi_miatoll
https://github.com/AhmedKazim-Dev/vendor_xiaomi_sm6250-common
```

## Number of ROM's you maintain officially
```
0
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Build Locally
```
## Free trial user or paid user?
```
Insert here
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
t.me/AKDiamondHacker
```

### GitHub username
```
https://github.com/AhmedKazim-Dev
```

**Comment by iamimmanuelraj** [comment]
Rejected !

Adding context and reason below @heisinbug @ralf979 
![image](https://user-images.githubusercontent.com/26855364/194681340-fb99e899-7942-439f-a9eb-7a3c7e946d2f.png)
![image](https://user-images.githubusercontent.com/26855364/194681345-45497f13-112d-4b6d-a8e1-4c6e13a74064.png)
