### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by romanxwalker** [PixelExtended/official_devices#7]
## Device you want to apply for
```
Redmi 9 / Poco M2 (lava)
```

## Device tree sources
```
https://github.com/romanxwalker/android_device_xiaomi_lava.git
https://github.com/romanxwalker/android_device_xiaomi_mt6768-common.git
https://github.com/romanxwalker/kernel_xiaomi_mt6768.git
https://github.com/romanxwalker/android_vendor_xiaomi_lava.git
```

## Number of ROM's you maintain officially
```
Zero
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Serverhub
```
## Free trial user or paid user?
```
paid
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
romanxwalker
```

### GitHub username
```
romanxwalker 
```

**Comment by iamimmanuelraj** [comment]
### -1

**Comment by heisinbug** [comment]
you don't run right after you are born
