### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by JayanthKandula** [PixelExtended/official_devices#8]
## Device you want to apply for
```
POCO F4/Redmi K40S
```

## Device tree sources

```
https://github.com/JayanthKandula/device_xiaomi_munch
https://github.com/JayanthKandula/device_xiaomi_sm8250-common
https://github.com/JayanthKandula/kernel_xiaomi_sm8250
https://gitlab.com/jayanth-coder/vendor-xiaomi-munch
https://gitlab.com/jayanth-coder/vendor-xiaomi-sm-8250-common
```

## Number of ROM's you maintain officially
```
0
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
I build locally
```
## Free trial user or paid user?
```
N/A
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
https://t.me/Jayanthk
```

### GitHub username
```
https://github.com/JayanthKandula
```

**Comment by heisinbug** [comment]
Any earlier release of Pex if so provide link .

**Comment by JayanthKandula** [comment]
https://sourceforge.net/projects/munch-pex/files/PixelExtended-5.2_munch-13.0-20221202-0551-UNOFFICIAL.zip/download
![photo_2022-12-02_16-23-13](https://user-images.githubusercontent.com/71193355/205276858-69402d5a-97ec-45e6-8575-ba620ae251b8.jpg)

**Comment by iamimmanuelraj** [comment]
-1

@ralf979 @heisinbug what do you say
