### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by RDS-007** [PixelExtended/official_devices#9]
## Device you want to apply for
```
Your device name : cepheus
```

## Device tree sources

```
https://github.com/user/device_brand_codename
https://github.com/user/kernel_brand_codename
https://github.com/user/vendor_brand_codename
```

## Number of ROM's you maintain officially
```
xtended before
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
locally
```
## Free trial user or paid user?
```
Insert here
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
RDS_07
```

### GitHub username
```
  RDS-007
```

**Comment by iamimmanuelraj** [comment]
You dont have any specia concern also, but you have not give your tree link....is that by mistake or intentional
